ompl:
  planning_plugin: ompl_interface/OMPLPlanner
  request_adapters: ""
  start_state_max_bounds_error: 0.1

  panda_arm:
    default_planner_config: RRTConnect
    planner_configs:
      - RRTConnect
      - RRT
      - RRTstar
      - PRM
    projection_evaluator: joints(panda_joint1,panda_joint2)
    longest_valid_segment_fraction: 0.005

  planner_configs:
    RRTConnect:
      type: geometric::RRTConnect
      range: 0.0
    RRT:
      type: geometric::RRT
      range: 0.0
      goal_bias: 0.05
    RRTstar:
      type: geometric::RRTstar
      range: 0.0
      goal_bias: 0.05
      delay_collision_checking: 1
    PRM:
      type: geometric::PRM
      max_nearest_neighbors: 10
